name: Act from Labels

on:
  pull_request:
    types: [labeled]

jobs:
  # Define variables from the PR Label
  define-variables:
    name: Define output variables
    runs-on: ubuntu-latest
    outputs:
      label_type: ${{ steps.set_label_type.outputs.label_type }}
      app_name: ${{ steps.set_app_name.outputs.app_name }}
    steps:
      - id: set_label_type
        name: Set Label Type
        run: |
          echo "label_type=$(echo ${{ github.event.label.name }} | awk '{split($0,a," / "); print a[1]}')" >> "${GITHUB_OUTPUT}"
      - id: set_app_name
        name: Set App Name
        run: |
          echo "app_name=$(echo ${{ github.event.label.name }} | awk '{split($0,a," / "); print a[2]}')" >> "${GITHUB_OUTPUT}"

  # Echo the output variables
  # echo-variables:
  #   name: Echo output variables
  #   runs-on: ubuntu-latest
  #   needs: define-variables
  #   steps:
  #     - id: echo_variables
  #       run: |
  #         echo "label_type: ${{ needs.define-variables.outputs.label_type }}"
  #         echo "app_name: ${{ needs.define-variables.outputs.app_name }}"

  # Test if statement
  test-if:
    name: Test if statement
    runs-on: ubuntu-latest
    needs: define-variables
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy / index') }}
    steps:
      - id: test_if
        run: |
          echo github.event.pull_request.labels
          echo "This ran..."